spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    view-names: thymeleaf/*
  autoconfigure: 
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
server:
  port: 8090
  error:
    whitelabel:
      enabled: true